//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.02 at 10:36:04 AM EDT 
//


package com.ram.spring.matrix.soap.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matrix complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matrix"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dataValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="matrixId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="matrixName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="positionX" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="positionY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matrix", namespace = "http://com.ram.spring/ws/matrix", propOrder = {
    "dataType",
    "dataValue",
    "matrixId",
    "matrixName",
    "positionX",
    "positionY"
})
public class Matrix {

    protected String dataType;
    protected String dataValue;
    protected long matrixId;
    protected String matrixName;
    protected int positionX;
    protected int positionY;

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the dataValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataValue() {
        return dataValue;
    }

    /**
     * Sets the value of the dataValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataValue(String value) {
        this.dataValue = value;
    }

    /**
     * Gets the value of the matrixId property.
     * 
     */
    public long getMatrixId() {
        return matrixId;
    }

    /**
     * Sets the value of the matrixId property.
     * 
     */
    public void setMatrixId(long value) {
        this.matrixId = value;
    }

    /**
     * Gets the value of the matrixName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatrixName() {
        return matrixName;
    }

    /**
     * Sets the value of the matrixName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatrixName(String value) {
        this.matrixName = value;
    }

    /**
     * Gets the value of the positionX property.
     * 
     */
    public int getPositionX() {
        return positionX;
    }

    /**
     * Sets the value of the positionX property.
     * 
     */
    public void setPositionX(int value) {
        this.positionX = value;
    }

    /**
     * Gets the value of the positionY property.
     * 
     */
    public int getPositionY() {
        return positionY;
    }

    /**
     * Sets the value of the positionY property.
     * 
     */
    public void setPositionY(int value) {
        this.positionY = value;
    }

}
